sonar.projectKey=Pilotioff_freelance
sonar.organization=pilotioff

sonar.sources=freelance-estimator-backend/src,freelance-estimator-frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/cypress/**

sonar.sourceEncoding=UTF-8
